import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import {
  bodyLine,
  chipDisabled,
  sectionBox,
  sectionHead,
  subLine,
} from "./workflow-page-styles";

// Owner-only secrets registry — METADATA ONLY.
//
// This page can never display a secret value, because the projection it reads
// contains none: /ops-data/secrets.json is generated by
// `scripts/secrets/secretsctl.mjs publish`, which serialises the registry
// minus every value and minus the filesystem path. Raw values live in
// ~/.secrets/values/<name> (0600) on the consumer account and are not served
// by any route.
//
// Read-only by construction, not by policy: the /ops surface is a static
// Caddy file_server with no application backend, so add/replace/disable are
// owner CLI verbs. The action chips below name them rather than faking a
// form that has nowhere to POST. See docs/secrets-mvp.md.
//
// Owner-gating is inherited: App.tsx renders LoginPage for any unauthenticated
// user before this route is reachable. No second auth system is introduced.

type LoadState = "loading" | "ready" | "empty" | "error";

export type SecretStatus = "active" | "disabled" | "expired";

export type SecretMeta = {
  name: string;
  type: string;
  purpose: string;
  consumer: string;
  owner: string;
  created: string;
  updated: string;
  expiry: string | null;
  status: SecretStatus;
};

type SecretsDoc = {
  schema?: number;
  generated_at?: string;
  secrets?: SecretMeta[];
};

// Defence in depth against a mis-generated projection: even if an upstream
// bug ever put a value-bearing key into the JSON, the UI drops it here and
// renders only the metadata allowlist. The browser must never hold a secret.
export function sanitizeSecret(raw: Record<string, unknown>): SecretMeta {
  return {
    name: String(raw.name ?? ""),
    type: String(raw.type ?? "other"),
    purpose: String(raw.purpose ?? ""),
    consumer: String(raw.consumer ?? ""),
    owner: String(raw.owner ?? ""),
    created: String(raw.created ?? ""),
    updated: String(raw.updated ?? raw.created ?? ""),
    expiry: raw.expiry == null ? null : String(raw.expiry),
    status: (["active", "disabled", "expired"].includes(String(raw.status))
      ? String(raw.status)
      : "active") as SecretStatus,
  };
}

export function statusLabel(status: SecretStatus): string {
  if (status === "disabled") return "מושבת";
  if (status === "expired") return "פג תוקף";
  return "פעיל";
}

export function statusColor(status: SecretStatus): string {
  if (status === "disabled") return "#6b7280";
  if (status === "expired") return "#b45309";
  return "#15803d";
}

// An absent projection is the normal state before the owner first publishes,
// not a failure. Distinguish it from a genuine parse/network error so the
// empty state can say something true.
async function fetchSecrets(): Promise<{ doc: SecretsDoc | null; missing: boolean }> {
  try {
    const r = await fetch("/ops-data/secrets.json", { cache: "no-store" });
    if (r.status === 404) return { doc: null, missing: true };
    if (!r.ok) return { doc: null, missing: false };
    return { doc: (await r.json()) as SecretsDoc, missing: false };
  } catch {
    return { doc: null, missing: false };
  }
}

export function OpsSecretsPage() {
  const [secrets, setSecrets] = useState<SecretMeta[]>([]);
  const [generatedAt, setGeneratedAt] = useState<string | null>(null);
  const [state, setState] = useState<LoadState>("loading");

  useEffect(() => {
    let cancelled = false;
    fetchSecrets().then(({ doc, missing }) => {
      if (cancelled) return;
      if (missing) {
        setState("empty");
        return;
      }
      if (doc == null) {
        setState("error");
        return;
      }
      const list = (doc.secrets ?? []).map((s) =>
        sanitizeSecret(s as unknown as Record<string, unknown>),
      );
      setSecrets(list);
      setGeneratedAt(doc.generated_at ?? null);
      setState(list.length === 0 ? "empty" : "ready");
    });
    return () => {
      cancelled = true;
    };
  }, []);

  return (
    <main
      dir="rtl"
      lang="he"
      data-testid="ops-secrets-page"
      style={{
        maxWidth: 720,
        margin: "0 auto",
        padding: "12px 14px 32px",
        fontFamily: "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif",
      }}
    >
      <nav style={{ marginBottom: 12 }}>
        <Link
          to="/ops"
          data-testid="ops-secrets-back"
          style={{ fontSize: 13, color: "#2563eb", textDecoration: "none" }}
        >
          ← חזרה לתפעול
        </Link>
      </nav>

      <h1 style={{ fontSize: 18, margin: "0 0 4px 0" }}>סודות — מרשם</h1>
      <p style={subLine}>
        מטא-דאטה בלבד. ערכי הסודות נשמרים בקבצים פרטיים בהרשאת בעלים בלבד ואינם
        נחשפים בדף הזה, ב-API או בדפדפן.
      </p>

      {state === "loading" && (
        <div data-testid="ops-secrets-loading" style={bodyLine}>
          טוען מרשם סודות…
        </div>
      )}

      {state === "error" && (
        <div data-testid="ops-secrets-error" role="alert" style={bodyLine}>
          לא ניתן לטעון את מרשם הסודות. נסה לרענן את הדף.
        </div>
      )}

      {state === "empty" && (
        <div data-testid="ops-secrets-empty" role="status" style={sectionBox}>
          <h2 style={sectionHead}>אין סודות רשומים עדיין</h2>
          <p style={bodyLine}>
            כדי לרשום סוד ראשון, הרץ בחשבון הצריכה:
            {" "}
            <code>node scripts/secrets/secretsctl.mjs add --name …</code>
            {" "}ואחריו{" "}
            <code>… publish</code>.
          </p>
        </div>
      )}

      {state === "ready" && (
        <section data-testid="ops-secrets-list" style={sectionBox}>
          <h2 style={sectionHead}>סודות רשומים ({secrets.length})</h2>
          <ul style={{ listStyle: "none", margin: 0, padding: 0 }}>
            {secrets.map((s) => (
              <li
                key={s.name}
                data-testid="ops-secret-row"
                style={{ padding: "8px 0", borderBottom: "1px solid #f1f5f9" }}
              >
                <div style={{ display: "flex", gap: 8, alignItems: "baseline", flexWrap: "wrap" }}>
                  <strong style={{ fontSize: 14 }}>{s.name}</strong>
                  <span
                    data-testid="ops-secret-status"
                    style={{ fontSize: 12, color: statusColor(s.status) }}
                  >
                    {statusLabel(s.status)}
                  </span>
                  <span style={{ fontSize: 12, color: "#6b7280" }}>{s.type}</span>
                </div>
                <div style={subLine}>{s.purpose}</div>
                <div style={subLine}>
                  צרכן: {s.consumer} · בעלים: {s.owner} · נוצר: {s.created} · עודכן:{" "}
                  {s.updated ? s.updated.slice(0, 10) : "—"} · תפוגה: {s.expiry ?? "ללא"}
                </div>
              </li>
            ))}
          </ul>
        </section>
      )}

      <section data-testid="ops-secrets-actions" style={sectionBox}>
        <h2 style={sectionHead}>פעולות</h2>
        <p style={subLine}>
          כתיבה מתבצעת ב-CLI בחשבון הצריכה בלבד — משטח /ops הוא קבצים סטטיים ללא
          שרת כתיבה, וערך סוד לעולם אינו עובר דרך הדפדפן.
        </p>
        <div>
          <span style={chipDisabled} title="secretsctl add">
            הוספת סוד
          </span>
          <span style={chipDisabled} title="secretsctl replace">
            החלפת ערך
          </span>
          <span style={chipDisabled} title="secretsctl disable">
            השבתה
          </span>
        </div>
        <p style={subLine}>
          השבתה היא מטא-דאטה בלבד ואינה מבטלת את האישור אצל הספק.
        </p>
      </section>

      {generatedAt && (
        <p data-testid="ops-secrets-generated" style={subLine}>
          עודכן: {generatedAt}
        </p>
      )}
    </main>
  );
}
